config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  # get 'profile/users/:id' => 'users#show', as: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'homes/top' => 'homes#top'
  get 'submissions/search' => 'submissions#search'
  # get 'submissions/new' => 'submissions#new'
  resources :submissions, only: %i[index new show create destroy] do
    resources :favorites, only: %i[index create destroy]
  end

  get 'users/unsubscribe' => 'users#unsubscribe'
  resources :users, only: %i[show edit destroy update] do
    get 'submissions' => 'favorites#index'
    resources :relationships, only: %i[create destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user

  belongs_to :submission
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/submission.rb
class Submission < ApplicationRecord
  # mount_uploaders :image, ImageUploader

  validates :submission_comment, length: { maximum: 200 }

  belongs_to :user

  has_many :favorites, dependent: :destroy

  has_many :submission_images, dependent: :destroy
  accepts_attachments_for :submission_images, attachment: :image, append: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      Submission.where(['submission_comment LIKE ?', "%#{search}%"])
    else
      Submission.none
    end
  end

  # FILE_NUMBER_LIMIT = 5

  # validate :validate_number_of_files

  # accepts_nested_attributes_for :

  # private

  # def validate_number_of_files
  #   return if images.length <= FILE_NUMBER_LIMIT
  #   errors.add(:images, "に添付できる画像は#{FILE_NUMBER_LIMIT}件までです。")
  # end
end

app/models/submission_image.rb
class SubmissionImage < ApplicationRecord
  belongs_to :submission
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :submissions, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  attachment :icon_image

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[emil password])
  end

  def after_sign_up_path_for(_resource)
    user_path(current_user.id)
  end

  def after_sign_in_path_for(_resource)
    submissions_path
  end

  def after_sign_out_path_for(_resource)
    homes_top_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    submission = Submission.find(params[:submission_id])
    favorite = current_user.favorites.new(submission_id: submission.id)
    favorite.save
    redirect_to submissions_path
  end

  def destroy
    submission = Submission.find(params[:submission_id])
    favorite = current_user.favorites.find_by(submission_id: submission.id)
    favorite.destroy
    redirect_to submissions_path
  end

  def index
    #  # @user = User.find_by(id: params[:id])
    #  # @user = current_user.id
    # 　# favorites = Favorite.where(user_id: @user)
    #  @submission = Submission.where(favorites: favorites)
    @user = current_user.id
    @submissions = Submission.includes(:favorites).where(favorites: { user_id: @user })
  end

  private

  def favorite_params
    params.require(:favorite).permit(:submission_id, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top; end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to user_path(current_user)
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to user_path(current_user)
  end

  def followings
    # user = User.find(params[:user_id])
    @users = current_user.followings
  end

  def followers
    # user = User.find(params[:user_id])
    @users = current_user.followers
  end

  private

  def relationship_params
    params.require(:relationship).permit(:followed_id, :follower_id)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def index
    @submissions = Submission.all
  end

  def show
    @submission = Submission.find(params[:id])
  end

  def new
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(submission_params)
    @submission.save
    redirect_to user_path(@submission.user_id)
  end

  def destroy
    @submission = Submission.find(params[:id])
    if @submission.destroy
      flash[:notice] = 'Delete Complete'
      redirect_to user_path(@submission.user.id)
    end
  end

  def search
    @submissions = Submission.new
    @submissions = if params[:submission_comment].present?
                     Submission.search(params[:submission_comment])
                   else
                     Submission.none
                   end
  end

  private

  def submission_params
    params.require(:submission).permit(:submission_comment,
                                       submission_images_images: []).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @submissions = @user.submissions
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = 'Delete Complete'
      redirect_to homes_top_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def unsubscribe
  end

  private

  def user_params
    params.require(:user).permit(:nick_name, :icon_image, :email, :password, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<main>
 <div class="container2">
  <% @submissions.each do |submission| %>
   <tr>
    <td><%= attachment_image_tag submission.user, :icon_image, size: "100x100", class:"icon",fallback: "virender-singh-hE0nmTffKtM-unsplash.jpg" %></td>
    <td><%= link_to user_path(submission.user_id) do %>
    <%= submission.user.nick_name %>
    <% end %></td>
    <td><%= submission.created_at.strftime('%Y/%m/%d') %></td>
   </tr>
  </div>
  <div class="container">
   <%= link_to submission_path(submission.id) do %>
   <% submission.submission_images.each do |image| %>
   <%= attachment_image_tag image, :image, size: "300x300" %>
   <% end %>
   <% end %>
  </div>
  <div class="container">
    <%= link_to submission_path(submission.id) do %>
    <%= submission.submission_comment %>
    <% end %>
  </div>
    <% end %>
</main>

app/views/homes/top.html.erb
<main>
 <div class="container">
  <h1>TOP</h1>
   <div class="row">
    <tr>
     <p class="word1">〜このサイトについて〜<br>このサイトは主にミニチュアやドールハ<br>ウスなどのSNS投稿サイトになります</p>
     <div align="right">
      <%= image_tag "giacomo-alonzi-2nIsxaBfHhc-unsplash.jpg", alt: "Rails icon", id: "assets", class: "image", width: "900px", height: "500" %></div>
   </div>
   <div class="row3">
    <h6 align="right">Unsplash URL→https://unsplash.com/photos/2nIsxaBfHhc?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink</h6>
   </div>
    </tr>
    <div class="row2">
     <tr>
      <p class="font1">小さな部屋を大きな世界に！<br>この世界もしくは、あなたの頭の中<br>の世界を、現実に再現してみませんか？</p>
       <div align="left">
        <%= image_tag "fidel-fernando-ioWVMYTrxpU-unsplash.jpg", alt: "Rails icon", id: "assets", class: "image", width: "700px", height: "500" %></div>
    </div>
     <div class="row3">
      <h6 align="left">Unsplash URL→https://unsplash.com/photos/ioWVMYTrxpU?utm_source=unsplash&utm_medium=referral&utm_content=creditShareLink</h6>
     </tr>
    </div>
 </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Origins</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

　　<%# self_css_path = "/assets/"+controller.controller_path  %>
    <%#= stylesheet_link_tag self_css_path, :media => "all" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link rel="stylesheet" media="all" href="<%#= asset_path(controller_path+'.css') %>" />-->
  </head>

  <body class='<%= "#{controller.controller_name}_#{controller.action_name}" %>'>
    <header>
     <% if user_signed_in? %>
      <div class="container1">
        <%= link_to 'Origins', homes_top_path, class:"logo" %></li>
        <div class="row1">
         <li class="item1"><%= link_to 'プロフィール', user_path(current_user.id),class:"link" %></li>
         <li class="item2"><%= link_to '投稿一覧', submissions_path,class:"link" %></li>
         <li class="item3"><%= link_to '投稿検索', submissions_search_path,class:"link" %></li>
         <li class="item4"><%= link_to 'いいね', user_submissions_path(current_user.id),class:"link" %></li>
         <li class="item5"><%= link_to 'ログアウト', destroy_user_session_path,method: :delete,class:"link" %></li>
        </ul>
      </div>
     </nav>
     <% else %>
      <div class="container1">
        <%= link_to 'Origins', homes_top_path, class:"logo" %></li>
        <div class="row1">
         <li class="item1"><%= link_to 'トップ', homes_top_path,class:"link" %></li>
         <li class="item2"><%= link_to 'サインアップ', new_user_registration_path,class:"link" %></li>
         <li class="item3"><%= link_to 'ログイン', new_user_session_path,class:"link" %></li>
        </ul>
      </div>
     </nav>
     <% end %>
    </header>
    <%= yield %>
   </body>
</html>

app/views/relationships/followers.html.erb
<main>
 <div class="container">
  <h2 class="title">フォロワーユーザーリスト</h2>
 </div>
  <% if @users.exists? %>
   <div class="container2">
    <% @users.each do |user| %>
        <td><%= link_to user_path(user.id) do %>
            <%= attachment_image_tag user, :icon_image, size: "100x100", class:"icon",fallback: "virender-singh-hE0nmTffKtM-unsplash.jpg" %>
            <% end %></td>
        <td><%= link_to user_path(user.id) do %>
            <%= user.nick_name %>
            <% end %></td>
  </div>
  <div class="introduction">
    <td><%= user.introduction %></td>
  </div>
    <% end %>
<% else %>
 <div class="title">
  <p>ユーザーはいません</p>
 </div>
<% end %>

app/views/relationships/followings.html.erb
<main>
 <div class="container">
  <h2 class="title">フォローユーザーリスト</h2>
 </div>
  <% if @users.exists? %>
   <div class="container2">
    <% @users.each do |user| %>
        <td><%= link_to user_path(user.id) do %>
            <%= attachment_image_tag user, :icon_image, size: "100x100", class:"icon",fallback: "virender-singh-hE0nmTffKtM-unsplash.jpg" %>
            <% end %></td>
        <td><%= link_to user_path(user.id) do %>
            <%= user.nick_name %>
            <% end %></td>
  </div>
  <div class="introduction">
    <td><%= user.introduction %></td>
  </div>
    <% end %>
<% else %>
 <div class="title">
  <p>ユーザーはいません</p>
 </div>
<% end %>

app/views/submissions/index.html.erb
<main>
 <div class="container2">
   <% @submissions.each do |submission| %>
   <tr>
     <td><%= link_to user_path(submission.user_id) do %>
     <%= attachment_image_tag submission.user, :icon_image, size: "100x100", class:"icon",fallback: "virender-singh-hE0nmTffKtM-unsplash.jpg" %>
     <% end %></td>
     <td><%= link_to user_path(submission.user_id) do %>
     <%= submission.user.nick_name %>
     <% end %></td>
     <td><%= submission.created_at.strftime('%Y/%m/%d') %></td>
   </tr>
  </div>
 <div class="container">
   <%= link_to submission_path(submission.id) do %>
   <% submission.submission_images.each do |image| %>
   <%= attachment_image_tag image, :image, size: "300x300" %>
   <% end %>
   <% end %>
  </div>
 <div class="container">
    <%= link_to submission_path(submission.id) do %>
    <%= submission.submission_comment %>
    <% end %>
  </div>
    <% end %>
</main>

app/views/submissions/new.html.erb
<main>
 <div class="container">
  <div class="row">
   <%= form_with model:@submission, local:true do |f| %>
   <div class="form-group">
    <%= f.label :写真選択 %>
    <%= f.attachment_field :submission_images_images, multiple: true %>
   </div>

   <div class="form-group">
    <%= f.label :コメント %>
    <%= f.text_field :submission_comment %></div>

   <div class="form-group">
    <%= f.submit :"新規投稿",class: "submit" %></div>
    <% end %>
  </div>
 </div>
</main>

app/views/submissions/search.html.erb
<main>
 <div class="search-form">
  <%= form_with url:submissions_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :submission_comment, :size=>"100" %>
    <%= f.submit "検索" %>
  <% end %>
 </div>

 <div class="container2">
   <% @submissions.each do |submission| %>
   <tr>
     <td><%= attachment_image_tag submission.user, :icon_image, size: "100x100", class:"icon",fallback: "virender-singh-hE0nmTffKtM-unsplash.jpg" %></td>
     <td><%= link_to user_path(submission.user_id) do %>
     <%= submission.user.nick_name %>
     <% end %></td>
     <td><%= submission.created_at.strftime('%Y/%m/%d') %></td>
   </tr>
  </div>
 </div>
 <div class="container">
   <%= link_to submission_path(submission.id) do %>
   <% submission.submission_images.each do |image| %>
   <%= attachment_image_tag image, :image, size: "400x400" %>
   <% end %>
   <% end %>
  </div>
 <div class="container">
    <%= link_to submission_path(submission.id) do %>
    <%= submission.submission_comment %>
    <% end %>
  </div>
    <% end %>
 </div>
</main>

app/views/submissions/show.html.erb
<main>
 <div class="container">
  <div class="row">
    <tr>
     <% if @submission.user.icon_image_id? %>
     <td class="local"><%= link_to user_path(@submission.user_id) do %>
     <%= attachment_image_tag @submission.user, :icon_image, size: "100x100", class:"icon" %>
     <% end %></td>
     <% else %>
     <td><%= link_to user_path(@submission.user_id) do %>
     <%= image_tag "virender-singh-hE0nmTffKtM-unsplash.jpg", size: "100x100", class:"icon" %>
     <% end %></td>
     <% end %>

     <td><%= link_to user_path(@submission.user_id) do %>
     <%= @submission.user.nick_name %>
     <% end %></td>
     <% if @submission.favorited_by?(current_user) %>
     <td><%= link_to submission_favorite_path(@submission.id), method: :delete do %>
     ♥<%= @submission.favorites.count %> いいね
     <% end %>
     </td>
     <% else %>
     <td><%= link_to submission_favorites_path(@submission.id), method: :post do %>
     ♡<%= @submission.favorites.count %> いいね
     <% end %>
     </td>
     <% end %>
     <td><%= @submission.created_at.strftime('%Y/%m/%d') %></td>
   </tr>
  </div>
 </div>
 <div class="container">
  <div class="row">
   <% @submission.submission_images.each do |image| %>
   <%= attachment_image_tag image, :image, size: "600x600" %>
   <% end %>
  </div>
 </div>
 <div class="container">
  <div class="row">
   <%= @submission.submission_comment %>
  </div>
 </div>
 <div class="container">
  <div class="row">
   <% if  @submission.user.id == current_user.id %>
   <%= link_to "投稿削除しますか？", submission_path, method: :delete, class: "del" %>
   <% end %>
  </div>
 </div>
</main>

app/views/users/edit.html.erb
<main>
 <div class="container">
  <div class="row">
   <% if current_user.id == @user.id %>
    <%= form_with model:@user, local:true do |f| %>
     <div class="item">
     <%= f.label :Icon %>
     <%= f.file_field :icon_image %></div>

    <div class="item">
     <%= f.label :Name %>
     <%= f.text_field :nick_name %></div>

    <div class="item">
     <%= f.label :Introduction %>
     <%= f.text_field:introduction %></div>

     <%= f.submit :"変更保存",class: "edit" %>
   <% end %>
   <% end %>

    <% if current_user.id == @user.id %>
     <%= link_to "退会", users_unsubscribe_path, class: "danger" %>
     <% else%>
    <% end %>

    </div>
  </div>
 </div>
</main>

app/views/users/show.html.erb
<main>
 <div class="follow">
  <% unless current_user == @user %>
  <% if current_user.following?(@user) %>
  <%= button_to "フォロー解除", user_relationship_path(@user.id), method: :delete, class:"releasebtn" %>
  <% else %>
  <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"followbtn" %>
  <% end %>
  <% end %>
 </div>

  <div class="container">
   <div class="row">
     <%= attachment_image_tag @user, :icon_image, size: "300x300", class:"icon", fallback:"virender-singh-hE0nmTffKtM-unsplash.jpg" %>
     <div class="test">
      <div class="w-100 pl-3">
       <%= @user.nick_name %>
       <% if current_user.id == @user.id %>
        <%= link_to '変更', edit_user_path(@user.id), class: "user_edit" %>
       <% end %>
       <%= link_to "＋", new_submission_path, class:"new_post" %>
      </div>
      <div class="w-100">
       <ul class="list"><%= link_to "フォローリスト", user_followings_path(@user.id),class:"btn btn-secondary" %>:<%= @user.followings.count %></ul>
       <ul class="list"><%= link_to "フォロワーリスト", user_followers_path(@user.id),class:"btn btn-secondary" %>:<%= @user.followers.count %></ul>
      </div>
     </div>

   </div>
   <div class="row2">
     <%= @user.introduction %>
   </div>
    <% @user.submissions.each do |submission| %>
     <div class="row">
       <% submission.submission_images.each do |image| %>
        <%= link_to submission_path(submission.id) do %>
        <%= attachment_image_tag image, :image, width: "300" %>
       <% end %>
       <% end %>
     </div>
     <div class="row3">
       <%= link_to submission_path(submission.id) do %>
       <%= submission.submission_comment %>
       <% end %>
     </div>
    <% end %>
 </div>
</main>

app/views/users/unsubscribe.html.erb
<main>
 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <h3>本当に退会しますか？</h3>
   </div>
    <div class="row">
     <tr>
      <h5>※一度退会してしまうと、データは残りませんので<br>ご注意ください。</h5>
     </tr>
    </div>

     <div class="row">
      <tr>
       <%= link_to "はい", user_path(current_user.id), class:"btn btn-info btn-sm", method: :delete, data: {comfirm: "Are you sure?"} %>
       :<%= link_to "いいえ", user_path(current_user.id), class:"btn btn-info btn-sm" %>
      </tr>
     </div>
  </div>
</main>